CREATE DATABASE if not EXISTS desafio_crud;

use desafio_crud;

CREATE TABLE tbl_libros (
  id INT(20) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(200) NOT NULL,
  id_api VARCHAR(100) NOT NULL,
  authors VARCHAR(100) NOT NULL,
  imagen VARCHAR(100) NOT NULL,
  comentario VARCHAR(100) NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);